# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78383199566a2f27208ac38d02df8dab6b2b771f629c6f52335559d317a8a4cf432408b0a881cad3aefedfa87bf9f7be953d7c2ef6d4ec24a9477575d63f38bf

test:
  secret_key_base: 0fa810800d5f2e76743ce7b2e5f712ab32ad46eca8d64bed7fb49cad9f96fea1612fc3540812c7585c4c1fa92cc289f525f8fbbb426a296cd140ce23f45b9dfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
